services:
  vault:
    image: hashicorp/vault:1.21.1
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: "https://vault.local:8200"
      VAULT_LOG_LEVEL: trace
    volumes:
      - ./config:/vault/config
      - ./data:/vault/data
      - ./tls:/vault/tls
      - ./logs:/vault/logs
    command: server
    networks:
      - vaultnet

networks:
  vaultnet:
    driver: bridge